/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CgPlayButtonR: typeof import('@kalimahapps/vue-icons/cg')['CgPlayButtonR']
    ChRefresh: typeof import('@kalimahapps/vue-icons/ch')['ChRefresh']
    EditAudioComponent: typeof import('./src/components/EditAudioComponent.vue')['default']
    EditTextComponent: typeof import('./src/components/EditTextComponent.vue')['default']
    FaCompress: typeof import('@kalimahapps/vue-icons/fa')['FaCompress']
    FaExpand: typeof import('@kalimahapps/vue-icons/fa')['FaExpand']
    FaGears: typeof import('@kalimahapps/vue-icons/fa')['FaGears']
    FaHouse: typeof import('@kalimahapps/vue-icons/fa')['FaHouse']
    FaPenToSquare: typeof import('@kalimahapps/vue-icons/fa')['FaPenToSquare']
    FaUser: typeof import('@kalimahapps/vue-icons/fa')['FaUser']
    FeCameraOff: typeof import('@kalimahapps/vue-icons/fe')['FeCameraOff']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
