/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChRefresh: typeof import('@kalimahapps/vue-icons/ch')['ChRefresh']
    copy: typeof import('./src/components/EditAudioComponent copy.vue')['default']
    EditAudioComponent: typeof import('./src/components/EditAudioComponent.vue')['default']
    EditTextComponent: typeof import('./src/components/EditTextComponent.vue')['default']
    FaBackward: typeof import('@kalimahapps/vue-icons/fa')['FaBackward']
    FaCompress: typeof import('@kalimahapps/vue-icons/fa')['FaCompress']
    FaExpand: typeof import('@kalimahapps/vue-icons/fa')['FaExpand']
    FaForward: typeof import('@kalimahapps/vue-icons/fa')['FaForward']
    FaGears: typeof import('@kalimahapps/vue-icons/fa')['FaGears']
    FaHouse: typeof import('@kalimahapps/vue-icons/fa')['FaHouse']
    FaPenToSquare: typeof import('@kalimahapps/vue-icons/fa')['FaPenToSquare']
    FaUser: typeof import('@kalimahapps/vue-icons/fa')['FaUser']
    FaVolumeHigh: typeof import('@kalimahapps/vue-icons/fa')['FaVolumeHigh']
    FaWandMagicSparkles: typeof import('@kalimahapps/vue-icons/fa')['FaWandMagicSparkles']
    FlFilledSave: typeof import('@kalimahapps/vue-icons/fl')['FlFilledSave']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
