export interface ServerDatabaseItem {
    id: number | null;
    letters: string | null;
    order: number | null;
    image: string | null;
    sound: string | null;
    type: number | null;
    unitId: number | null;
    rewardType: number | null;
    reward: string | null;
    grouping: number | null;
    lastModified: string | null;
    text: string | null;
    deleted: boolean | null;
    version: number | null;
    loginid: string | null;
    uniqueId: string | null;
    databaseId: number | null;
    appId: number | null;
}
